apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: echo-api-product-sample
spec:
  applicationPlans:
    plan_basic:
      limits:
        - metricMethodRef:
            systemName: hits
          period: day
          value: 100
      name: Basic
    plan_unlimited:
      name: Unlimited
  providerAccountRef:
    name: tenant-secret
  name: Operator Product Echo API
  systemName: echo_api_product
  description: Echo API Product
  backendUsages:
    echo_api_backend:
      path: /
